package types

const (
	Bigint       = "bigint"
	Bigserial    = "bigserial"
	Bit          = "bit"
	Varbit       = "varbit"
	Bool         = "bool"
	Box          = "box"
	Bytea        = "bytea"
	Char         = "char"
	Varchar      = "varchar"
	Cidr         = "cidr"
	Circle       = "circle"
	Date         = "date"
	Float8       = "float8"
	Inet         = "inet"
	Int          = "int"
	Interval     = "interval"
	Json         = "json"
	Jsonb        = "jsonb"
	Line         = "line"
	Lseg         = "lseg"
	Macaddr      = "macaddr"
	Macaddr8     = "macaddr8"
	Money        = "money"
	Decimal      = "decimal"
	Path         = "path"
	PgLsn        = "pg_lsn"
	PgSnapshot   = "pg_snapshot"
	Point        = "point"
	Polygon      = "polygon"
	Real         = "real"
	Smallint     = "smallint"
	Smallserial  = "smallserial"
	Serial       = "serial"
	Text         = "text"
	Time         = "time"
	Timetz       = "timetz"
	Timestamp    = "timestamp"
	Timestamptz  = "timestamptz"
	Tsquery      = "tsquery"
	Tsvector     = "tsvector"
	TxidSnapshot = "txid_snapshot"
	Uuid         = "uuid"
	Xml          = "xml"
)
